root: true

extends:
  - eslint:recommended
  - google
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:wc/recommended
  - plugin:import/recommended
  - plugin:import/typescript

env:
  browser: true
  es2021: true

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
  sourceType: module

plugins:
  - '@typescript-eslint'
  - import
  - wc

settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: 'package/*/tsconfig.json'
  wc:
    elementBaseClasses:
      - LitElement
      # TODO: Add other classes

rules:
  max-len:
    - warn
    - code: 120
  no-eval:
    - error
    - allowIndirect: true
  no-floating-decimal: error
  space-infix-ops: error
  new-cap:
    - error
    - capIsNewExceptionPattern: 'Mixin$'
  '@typescript-eslint/explicit-function-return-type': error
  'import/order':
    - error
    - groups:
        - 'builtin'
        - 'external'
        - 'internal'
        - - 'parent'
          - 'sibling'
          - 'index'
        - 'type'
      'newlines-between': 'always'
      alphabetize:
        order: asc
        caseInsensitive: true

  # TODO: Enable in future
  import/no-unresolved: off
  require-jsdoc: off
  valid-jsdoc: off
