version: '2.4'

networks:
  web:
    external:
      name: web-proxy

services:
  pwa:
    build: .

    networks:
      - web

    cpu_shares: 1024
    mem_limit: 1g

    restart: unless-stopped
    tty: true

    logging:
      driver: json-file
      options:
        max-size: '12m'
        max-file: '2'

    labels:
      traefik.enable: true
      traefik.backend: salavat-pwa
      traefik.port: 8080
      traefik.frontend.rule: Host:salav.at
      traefik.frontend.entryPoints: http, https
      traefik.frontend.redirect.entryPoint: https
