name: Lint

on:
  pull_request:
  push:
    branches:
      - next
      - main
      - release/*

env:
  NODE_VERSION: '16.x'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: yarn lint
